openapi: 3.0.3
info:
  title: お気に入り登録API
  description: ECサイトにおける、お気に入り登録用のAPI仕様書
  version: 1.0.0

servers:
  - url: http://localhost/api
    description: ローカル環境

paths:
  /favorites:
    post:
      summary: お気に入り登録
      description: ログイン中のユーザーが商品をお気に入り登録します。
      tags:
        - お気に入り
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - item_id
              properties:
                item_id:
                  type: integer
                  example: 123
      responses:
        '201':
          description: 登録成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: お気に入りに登録しました。
                  favorite:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      user_id:
                        type: integer
                        example: 10
                      item_id:
                        type: integer
                        example: 123
                      created_at:
                        type: string
                        format: date-time
                        example: 2025-05-16T12:00:00Z
        '401':
          description: 認証エラー（未ログイン）
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
        '422':
          description: バリデーションエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: バリデーションエラー。
                  errors:
                    type: object
                    properties:
                      item_id:
                        type: array
                        items:
                          type: string
                        example: ["指定された商品IDは存在しません。"]
        '409':
          description: 既にお気に入り登録済み
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: すでにお気に入り登録済みです。

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
